server:
  port: 8097 # bu applicationin port numarasini yazdik
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false  # kendisi eureka oldugu icin bir yere kaydolmayacak o yuzden 2 yere false yazildi
    fetchRegistry: false #  Eureka sunucusunda kay?tl? olan di?er servisleri bilgilerini yerel olarak saklayacak ve bunlar? kullanarak servisleri dinamik olarak bulabilecektir.
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
