eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8097/eureka
      # !!! yukarda discovery server adresini soyluyoruz

spring:
  datasource:
    url: jdbc:h2:mem:testdb;
    driverClassName: org.h2.Driver
    username: sa # !!! H2 oldugu icin pass girmeye gerek yok
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true