server:
  port: 8090

spring:
  application:
    name: config

  profiles:
    active:
      - native

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8097/eureka  # !!! eureka nin adresini yaziyoruz